# GitHub Sponsors
github: [amangautamm]

# Buy Me a Coffee
buy_me_a_coffee: amangautamm

# Ko-fi
ko_fi: amangautamm

# Open Collective
# open_collective: YOUR_PROJECT

# Patreon
# patreon: amangautamm
